---
# ansible-role-miserver-support tasks file

- name: purpose file
  lineinfile:
    path: /usr/local/etc/purpose
    regexp: "^Purpose:"
    line: "Purpose: {{ mcommunity_purpose }}"
  when:
    - mcommunity_purpose is defined
    - mcommunity_purpose is not none

- name: provision accounts
  command: "/usr/local/sbin/ldgrp2accts --noverify {{ item }}"
  with_items: "{{ mcommunity_group_accounts }}"
  register: ldgrp2accts_result
  when:
    - mcommunity_group_accounts is defined
    - mcommunity_group_accounts is not none

- name: provisioning results
  debug:
    msg: "{{ item }}"
  with_items: "{{ ldgrp2accts_result | json_query('results[].stdout') }}"
  when:
    - ldgrp2accts_result is defined
    - ldgrp2accts_result is not none

- name: delete users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ miserver_userdel }}"
  when:
    - miserver_userdel is defined
    - miserver_userdel is not none
